version: '3.4'

services:
  web:
    build:
      context: ./
    # depends_on:
    #   - db
    # environment:
    #   DATABASE_URI: postgresql+psycopg2://postgres:postgres20930988/flask_api
    # networks:
    #   - default
    command: python manage.py runserver --host 0.0.0.0
    volumes:
      - ./app:/usr/src/flask-api/
      # - ./migrations:/usr/src/flask-api/migrations
    ports:
      - 5000:5000
    # volumes:
    #   - ./app:/usr/src/app/app
    #   - ./migrations:/usr/src/app/migrations
    env_file:
      - ./.env
    # restart: always

  # db:
  #   environment:
  #     POSTGRES_DB: flask_api
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres20930988
  #   image: postgres
  #   networks:
  #     - default
  #   ports:
  #     - 5433:5432
  #   restart: always
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data