version: '3.4'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      DATABASE_URI: postgresql+psycopg2://postgres:postgres20930988/flask_api
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    env_file:
      - ./.windows.env
    restart: always

  db:
    environment:
      POSTGRES_DB: flask_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres20930988
    image: postgres:latest
    networks:
      - default
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data