version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: flask_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres20930988
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data