version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: flask_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres20930988
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: ./
    command: flask run --host 0.0.0.0
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db