name: Python application
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; 
    - name: Test with pytest
      run: |
        pytest --cov=app --cov-report=term-missing
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        parallel: true
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Testingddddd
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "flask-api-starter-template"
        heroku_email: "harungachanjagitundu@gmail.com"
        usedocker: true